// Generated by zidl from types.idl — DO NOT EDIT

#ifndef TYPES_HPP
#define TYPES_HPP

#include <cstdint>
#include <string>
#include <vector>
#include <array>
#include <stdexcept>
#include "zidl_cdr.h"

enum class Color : uint32_t {
    RED = 0,
    GREEN = 1,
    BLUE = 2
}; // enum class Color

struct Point {
    int32_t x{};
    int32_t y{};
}; // struct Point

struct Sample {
    uint32_t id{};
    bool b{};
    uint8_t u8_val{};
    int16_t s16_val{};
    uint16_t u16_val{};
    int32_t s32_val{};
    uint32_t u32_val{};
    int64_t s64_val{};
    uint64_t u64_val{};
    float f32_val{};
    double f64_val{};
    std::string str{};
    std::string bstr{};
    std::vector<int32_t> nums{};
    int32_t arr[3];
    ::Color clr{};
    ::Point nested{};
}; // struct Sample

struct Frame {
    uint32_t seq_num{};
    std::string topic{};
}; // struct Frame

struct Beacon {
    uint32_t id{};
    std::string payload{};
}; // struct Beacon

class Greeter {
public:
    virtual ~Greeter() = default;
    virtual std::string greet(std::string name) = 0;
    virtual void reset() = 0;
    virtual int32_t count() const = 0;
}; // class Greeter

class AdvancedGreeter : public ::Greeter {
public:
    virtual ~AdvancedGreeter() = default;
    virtual void greetAdvanced(std::string name) = 0;
}; // class AdvancedGreeter

#endif // TYPES_HPP
