// Generated by zidl from types.idl — DO NOT EDIT

import java.util.List;
import java.util.ArrayList;

public class Types {
    private static void _cdrAlign(java.nio.ByteBuffer _buf, int _cdrBase, int _align) {
        if (_align <= 1) return;
        int _p = (_buf.position() - _cdrBase) % _align;
        if (_p != 0) _buf.position(_buf.position() + (_align - _p));
    }
    private static void _cdrWriteString(java.nio.ByteBuffer _buf, int _cdrBase, String _s) {
        _cdrAlign(_buf, _cdrBase, 4);
        byte[] _bytes = _s.getBytes(java.nio.charset.StandardCharsets.UTF_8);
        _buf.putInt(_bytes.length + 1); _buf.put(_bytes); _buf.put((byte)0);
    }
    private static String _cdrReadString(java.nio.ByteBuffer _buf, int _cdrBase) {
        _cdrAlign(_buf, _cdrBase, 4);
        int _len = _buf.getInt(); if (_len <= 0) return "";
        byte[] _bytes = new byte[_len - 1]; _buf.get(_bytes); _buf.get();
        return new String(_bytes, java.nio.charset.StandardCharsets.UTF_8);
    }
    private static void _cdrWriteFixed(java.nio.ByteBuffer _buf, int _d, int _s, double _v) {
        int _n = (_d / 2) + 1; int _n2 = _n * 2; int _pad = _n2 - _d - 1;
        boolean _neg = _v < 0.0;
        double _sf = Math.pow(10, _s); long _iv = (long)(Math.abs(_v) * _sf + 0.5);
        byte[] _dig = new byte[_d];
        for (int _i = _d - 1; _i >= 0; _i--) { _dig[_i] = (byte)(_iv % 10); _iv /= 10; }
        byte[] _nib = new byte[_n2];
        for (int _i = 0; _i < _d; _i++) _nib[_pad + _i] = _dig[_i];
        _nib[_n2 - 1] = _neg ? (byte)0x0D : (byte)0x0C;
        byte[] _bcd = new byte[_n];
        for (int _i = 0; _i < _n; _i++) _bcd[_i] = (byte)((_nib[2*_i] << 4) | _nib[2*_i+1]);
        _buf.put(_bcd);
    }
    private static double _cdrReadFixed(java.nio.ByteBuffer _buf, int _d, int _s) {
        int _n = (_d / 2) + 1; int _n2 = _n * 2; int _pad = _n2 - _d - 1;
        byte[] _bcd = new byte[_n]; _buf.get(_bcd);
        byte[] _nib = new byte[_n2];
        for (int _i = 0; _i < _n; _i++) { _nib[2*_i] = (byte)((_bcd[_i]>>4)&0x0F); _nib[2*_i+1] = (byte)(_bcd[_i]&0x0F); }
        long _iv = 0; for (int _k = 0; _k < _d; _k++) _iv = _iv * 10 + _nib[_pad + _k];
        boolean _neg = (_nib[_n2-1] == 0x0D || _nib[_n2-1] == 0x0B);
        double _r = (double)_iv / Math.pow(10, _s); return _neg ? -_r : _r;
    }

    private static byte[] _cdrComputeKeyHash(java.nio.ByteBuffer _buf) {
        int _len = _buf.position();
        byte[] _key = new byte[_len];
        _buf.position(0); _buf.get(_key);
        if (_len <= 16) {
            byte[] _out = new byte[16];
            System.arraycopy(_key, 0, _out, 0, _len);
            return _out;
        }
        try { return java.security.MessageDigest.getInstance("MD5").digest(_key); }
        catch (java.security.NoSuchAlgorithmException _e) { throw new IllegalStateException(_e); }
    }

    private static int _cdrDetectXcdr(byte[] _payload) {
        int _id = ((_payload[0] & 0xFF) << 8) | (_payload[1] & 0xFF);
        if (_id == 0x0001) return 1;
        if (_id == 0x0007) return 2;
        throw new IllegalArgumentException("zidl: unsupported CDR encapsulation id 0x" + Integer.toHexString(_id));
    }

    public enum Color {
        RED(0),
        GREEN(1),
        BLUE(2);

        private final int value;
        private Color(int value) { this.value = value; }

        public int getValue() { return value; }

        public static Color valueOf(int v) {
            for (Color _e : values()) { if (_e.value == v) return _e; }
            throw new RuntimeException("Unknown Color value: " + v);
        }
    } // Color

    public static class Point implements java.io.Serializable {
        private static final long serialVersionUID = 1L;
        private int x;
        private int y;

        public Point() {
            this.x = 0;
            this.y = 0;
        }

        public static Point defaultValue() {
            return new Point();
        }

        public Point(int x, int y) {
            this.x = x;
            this.y = y;
        }

        public int get_x() { return x; }
        public void set_x(int x) { this.x = x; }

        public int get_y() { return y; }
        public void set_y(int y) { this.y = y; }

        public static final boolean HAS_KEY = false;

        public void serialize(java.nio.ByteBuffer _buf, int _cdrBase, int _xcdrVersion) {
            _buf.order(java.nio.ByteOrder.LITTLE_ENDIAN);
            _cdrAlign(_buf, _cdrBase, 4); _buf.putInt(this.x);
            _cdrAlign(_buf, _cdrBase, 4); _buf.putInt(this.y);
        }

        public static Point deserializeFrom(java.nio.ByteBuffer _buf, int _cdrBase, int _xcdrVersion) {
            _buf.order(java.nio.ByteOrder.LITTLE_ENDIAN);
            Point _out = new Point();
            _cdrAlign(_buf, _cdrBase, 4); _out.x = _buf.getInt();
            _cdrAlign(_buf, _cdrBase, 4); _out.y = _buf.getInt();
            return _out;
        }

        public static void skip(java.nio.ByteBuffer _buf, int _cdrBase, int _xcdrVersion) {
            _buf.order(java.nio.ByteOrder.LITTLE_ENDIAN);
            _cdrAlign(_buf, _cdrBase, 4); _buf.getInt();
            _cdrAlign(_buf, _cdrBase, 4); _buf.getInt();
        }
    } // Point

    public static class Sample implements java.io.Serializable {
        private static final long serialVersionUID = 1L;
        private int id;
        private boolean b;
        private byte u8_val;
        private short s16_val;
        private short u16_val;
        private int s32_val;
        private int u32_val;
        private long s64_val;
        private long u64_val;
        private float f32_val;
        private double f64_val;
        private String str;
        private String bstr;
        private java.util.List<Integer> nums;
        private int[] arr;
        private Color clr;
        private Point nested;

        public Sample() {
            this.id = 0;
            this.b = false;
            this.u8_val = 0;
            this.s16_val = 0;
            this.u16_val = 0;
            this.s32_val = 0;
            this.u32_val = 0;
            this.s64_val = 0;
            this.u64_val = 0;
            this.f32_val = 0.0f;
            this.f64_val = 0.0;
            this.str = "";
            this.bstr = "";
            this.nums = new java.util.ArrayList<>();
            this.arr = new int[3];
            this.clr = Color.values()[0];
            this.nested = new Point();
        }

        public static Sample defaultValue() {
            return new Sample();
        }

        public Sample(int id, boolean b, byte u8_val, short s16_val, short u16_val, int s32_val, int u32_val, long s64_val, long u64_val, float f32_val, double f64_val, String str, String bstr, java.util.List<Integer> nums, int[] arr, Color clr, Point nested) {
            this.id = id;
            this.b = b;
            this.u8_val = u8_val;
            this.s16_val = s16_val;
            this.u16_val = u16_val;
            this.s32_val = s32_val;
            this.u32_val = u32_val;
            this.s64_val = s64_val;
            this.u64_val = u64_val;
            this.f32_val = f32_val;
            this.f64_val = f64_val;
            this.str = str;
            this.bstr = bstr;
            this.nums = nums;
            this.arr = arr;
            this.clr = clr;
            this.nested = nested;
        }

        public int get_id() { return id; }
        public void set_id(int id) { this.id = id; }

        public boolean get_b() { return b; }
        public void set_b(boolean b) { this.b = b; }

        public byte get_u8_val() { return u8_val; }
        public void set_u8_val(byte u8_val) { this.u8_val = u8_val; }

        public short get_s16_val() { return s16_val; }
        public void set_s16_val(short s16_val) { this.s16_val = s16_val; }

        public short get_u16_val() { return u16_val; }
        public void set_u16_val(short u16_val) { this.u16_val = u16_val; }

        public int get_s32_val() { return s32_val; }
        public void set_s32_val(int s32_val) { this.s32_val = s32_val; }

        public int get_u32_val() { return u32_val; }
        public void set_u32_val(int u32_val) { this.u32_val = u32_val; }

        public long get_s64_val() { return s64_val; }
        public void set_s64_val(long s64_val) { this.s64_val = s64_val; }

        public long get_u64_val() { return u64_val; }
        public void set_u64_val(long u64_val) { this.u64_val = u64_val; }

        public float get_f32_val() { return f32_val; }
        public void set_f32_val(float f32_val) { this.f32_val = f32_val; }

        public double get_f64_val() { return f64_val; }
        public void set_f64_val(double f64_val) { this.f64_val = f64_val; }

        public String get_str() { return str; }
        public void set_str(String str) { this.str = str; }

        public String get_bstr() { return bstr; }
        public void set_bstr(String bstr) { this.bstr = bstr; }

        public java.util.List<Integer> get_nums() { return nums; }
        public void set_nums(java.util.List<Integer> nums) { this.nums = nums; }

        public int[] get_arr() { return arr; }
        public void set_arr(int[] arr) { this.arr = arr; }

        public Color get_clr() { return clr; }
        public void set_clr(Color clr) { this.clr = clr; }

        public Point get_nested() { return nested; }
        public void set_nested(Point nested) { this.nested = nested; }

        public static final boolean HAS_KEY = true;

        public void serialize(java.nio.ByteBuffer _buf, int _cdrBase, int _xcdrVersion) {
            _buf.order(java.nio.ByteOrder.LITTLE_ENDIAN);
            _cdrAlign(_buf, _cdrBase, 4); _buf.putInt(this.id);
            _buf.put((byte)(this.b ? 1 : 0));
            _buf.put(this.u8_val);
            _cdrAlign(_buf, _cdrBase, 2); _buf.putShort(this.s16_val);
            _cdrAlign(_buf, _cdrBase, 2); _buf.putShort(this.u16_val);
            _cdrAlign(_buf, _cdrBase, 4); _buf.putInt(this.s32_val);
            _cdrAlign(_buf, _cdrBase, 4); _buf.putInt(this.u32_val);
            _cdrAlign(_buf, _cdrBase, _xcdrVersion == 1 ? 8 : 4); _buf.putLong(this.s64_val);
            _cdrAlign(_buf, _cdrBase, _xcdrVersion == 1 ? 8 : 4); _buf.putLong(this.u64_val);
            _cdrAlign(_buf, _cdrBase, 4); _buf.putFloat(this.f32_val);
            _cdrAlign(_buf, _cdrBase, _xcdrVersion == 1 ? 8 : 4); _buf.putDouble(this.f64_val);
            _cdrWriteString(_buf, _cdrBase, this.str);
            _cdrWriteString(_buf, _cdrBase, this.bstr);
            _cdrAlign(_buf, _cdrBase, 4); _buf.putInt(this.nums.size());
            for (Integer _e : this.nums) {
                _cdrAlign(_buf, _cdrBase, 4); _buf.putInt(_e);
            }
            for (int _d0 = 0; _d0 < 3; _d0++) {
                _cdrAlign(_buf, _cdrBase, 4); _buf.putInt(this.arr[_d0]);
            }
            _cdrAlign(_buf, _cdrBase, 4); _buf.putInt(this.clr.getValue());
            this.nested.serialize(_buf, _cdrBase, _xcdrVersion);
        }

        public static Sample deserializeFrom(java.nio.ByteBuffer _buf, int _cdrBase, int _xcdrVersion) {
            _buf.order(java.nio.ByteOrder.LITTLE_ENDIAN);
            Sample _out = new Sample();
            _cdrAlign(_buf, _cdrBase, 4); _out.id = _buf.getInt();
            _out.b = _buf.get() != 0;
            _out.u8_val = _buf.get();
            _cdrAlign(_buf, _cdrBase, 2); _out.s16_val = _buf.getShort();
            _cdrAlign(_buf, _cdrBase, 2); _out.u16_val = _buf.getShort();
            _cdrAlign(_buf, _cdrBase, 4); _out.s32_val = _buf.getInt();
            _cdrAlign(_buf, _cdrBase, 4); _out.u32_val = _buf.getInt();
            _cdrAlign(_buf, _cdrBase, _xcdrVersion == 1 ? 8 : 4); _out.s64_val = _buf.getLong();
            _cdrAlign(_buf, _cdrBase, _xcdrVersion == 1 ? 8 : 4); _out.u64_val = _buf.getLong();
            _cdrAlign(_buf, _cdrBase, 4); _out.f32_val = _buf.getFloat();
            _cdrAlign(_buf, _cdrBase, _xcdrVersion == 1 ? 8 : 4); _out.f64_val = _buf.getDouble();
            _out.str = _cdrReadString(_buf, _cdrBase);
            _out.bstr = _cdrReadString(_buf, _cdrBase);
            _cdrAlign(_buf, _cdrBase, 4); int _n__out_nums = _buf.getInt();
            _out.nums = new java.util.ArrayList<>(_n__out_nums);
            for (int _i__out_nums = 0; _i__out_nums < _n__out_nums; _i__out_nums++) {
                _cdrAlign(_buf, _cdrBase, 4); _out.nums.add(_buf.getInt());
            }
            for (int _d0 = 0; _d0 < 3; _d0++) {
                _cdrAlign(_buf, _cdrBase, 4); _out.arr[_d0] = _buf.getInt();
            }
            _cdrAlign(_buf, _cdrBase, 4); _out.clr = Color.valueOf(_buf.getInt());
            _out.nested = Point.deserializeFrom(_buf, _cdrBase, _xcdrVersion);
            return _out;
        }

        public static void skip(java.nio.ByteBuffer _buf, int _cdrBase, int _xcdrVersion) {
            _buf.order(java.nio.ByteOrder.LITTLE_ENDIAN);
            _cdrAlign(_buf, _cdrBase, 4); _buf.getInt();
            _buf.get();
            _buf.get();
            _cdrAlign(_buf, _cdrBase, 2); _buf.getShort();
            _cdrAlign(_buf, _cdrBase, 2); _buf.getShort();
            _cdrAlign(_buf, _cdrBase, 4); _buf.getInt();
            _cdrAlign(_buf, _cdrBase, 4); _buf.getInt();
            _cdrAlign(_buf, _cdrBase, _xcdrVersion == 1 ? 8 : 4); _buf.getLong();
            _cdrAlign(_buf, _cdrBase, _xcdrVersion == 1 ? 8 : 4); _buf.getLong();
            _cdrAlign(_buf, _cdrBase, 4); _buf.getInt();
            _cdrAlign(_buf, _cdrBase, _xcdrVersion == 1 ? 8 : 4); _buf.getLong();
            _cdrReadString(_buf, _cdrBase);
            _cdrReadString(_buf, _cdrBase);
            { _cdrAlign(_buf, _cdrBase, 4); int _n = _buf.getInt();
              for (int _i = 0; _i < _n; _i++) {
                _cdrAlign(_buf, _cdrBase, 4); _buf.getInt();
              }
            }
            for (int _sk0 = 0; _sk0 < 3; _sk0++) {
                _cdrAlign(_buf, _cdrBase, 4); _buf.getInt();
            }
            _cdrAlign(_buf, _cdrBase, 4); _buf.getInt();
            Point.skip(_buf, _cdrBase, _xcdrVersion);
        }

        protected void serializeKeyFields(java.nio.ByteBuffer _buf, int _cdrBase, int _xcdrVersion) {
            _cdrAlign(_buf, _cdrBase, 4); _buf.putInt(this.id);
        }

        public void serializeKey(java.nio.ByteBuffer _buf, int _cdrBase, int _xcdrVersion) {
            _buf.order(java.nio.ByteOrder.LITTLE_ENDIAN);
            serializeKeyFields(_buf, _cdrBase, _xcdrVersion);
        }

        public static Sample deserializeKey(java.nio.ByteBuffer _buf, int _cdrBase, int _xcdrVersion) {
            _buf.order(java.nio.ByteOrder.LITTLE_ENDIAN);
            Sample _out = new Sample();
            deserializeKeyInto(_out, _buf, _cdrBase, _xcdrVersion);
            return _out;
        }

        protected static void deserializeKeyInto(Sample _out, java.nio.ByteBuffer _buf, int _cdrBase, int _xcdrVersion) {
            _cdrAlign(_buf, _cdrBase, 4); _out.id = _buf.getInt();
        }

        public byte[] computeKeyHash() {
            int _cap = 256;
            while (true) {
                java.nio.ByteBuffer _buf = java.nio.ByteBuffer.allocate(_cap).order(java.nio.ByteOrder.BIG_ENDIAN);
                try {
                    serializeKeyFields(_buf, 0, 1);
                    return _cdrComputeKeyHash(_buf);
                } catch (java.nio.BufferOverflowException _e) {
                    _cap *= 2;
                }
            }
        }

        public static byte[] computeKeyHashFromCdr(byte[] _payload) {
            java.nio.ByteBuffer _buf = java.nio.ByteBuffer.wrap(_payload).order(java.nio.ByteOrder.LITTLE_ENDIAN);
            int _xcdrVersion = _cdrDetectXcdr(_payload);
            _buf.position(4);
            Sample _obj = deserializeFrom(_buf, 4, _xcdrVersion);
            return _obj.computeKeyHash();
        }

        public static Object getFieldFromCdr(byte[] _payload, String _field) {
            java.nio.ByteBuffer _buf = java.nio.ByteBuffer.wrap(_payload).order(java.nio.ByteOrder.LITTLE_ENDIAN);
            int _xcdrVersion = _cdrDetectXcdr(_payload);
            _buf.position(4);
            int _fi = fieldIndex(_field);
            Sample _obj = deserializeSelected(_buf, 4, _xcdrVersion, _fi < 0 ? 0L : (1L << _fi));
            switch (_field) {
                case "id": return (long) _obj.id;
                case "b": return (_obj.b ? 1L : 0L);
                case "u8_val": return (long) _obj.u8_val;
                case "s16_val": return (long) _obj.s16_val;
                case "u16_val": return (long) _obj.u16_val;
                case "s32_val": return (long) _obj.s32_val;
                case "u32_val": return (long) _obj.u32_val;
                case "s64_val": return (long) _obj.s64_val;
                case "u64_val": return (long) _obj.u64_val;
                case "f32_val": return (double) _obj.f32_val;
                case "f64_val": return (double) _obj.f64_val;
                case "str": return _obj.str;
                case "bstr": return _obj.bstr;
                case "clr": return (long) _obj.clr.getValue();
                default: return null;
            }
        }

        public static final long KEY_FIELD_MASK = (1L << 0);
        public static int fieldIndex(String _name) {
            switch (_name) {
                case "id": return 0;
                case "b": return 1;
                case "u8_val": return 2;
                case "s16_val": return 3;
                case "u16_val": return 4;
                case "s32_val": return 5;
                case "u32_val": return 6;
                case "s64_val": return 7;
                case "u64_val": return 8;
                case "f32_val": return 9;
                case "f64_val": return 10;
                case "str": return 11;
                case "bstr": return 12;
                case "nums": return 13;
                case "arr": return 14;
                case "clr": return 15;
                case "nested": return 16;
                default: return -1;
            }
        }

        public static Sample deserializeSelected(java.nio.ByteBuffer _buf, int _cdrBase, int _xcdrVersion, long _want) {
            _buf.order(java.nio.ByteOrder.LITTLE_ENDIAN);
            Sample _out = new Sample();
            if ((_want & (1L << 0)) != 0) {
                _cdrAlign(_buf, _cdrBase, 4); _out.id = _buf.getInt();
            } else {
                _cdrAlign(_buf, _cdrBase, 4); _buf.getInt();
            }
            if ((_want & (1L << 1)) != 0) {
                _out.b = _buf.get() != 0;
            } else {
                _buf.get();
            }
            if ((_want & (1L << 2)) != 0) {
                _out.u8_val = _buf.get();
            } else {
                _buf.get();
            }
            if ((_want & (1L << 3)) != 0) {
                _cdrAlign(_buf, _cdrBase, 2); _out.s16_val = _buf.getShort();
            } else {
                _cdrAlign(_buf, _cdrBase, 2); _buf.getShort();
            }
            if ((_want & (1L << 4)) != 0) {
                _cdrAlign(_buf, _cdrBase, 2); _out.u16_val = _buf.getShort();
            } else {
                _cdrAlign(_buf, _cdrBase, 2); _buf.getShort();
            }
            if ((_want & (1L << 5)) != 0) {
                _cdrAlign(_buf, _cdrBase, 4); _out.s32_val = _buf.getInt();
            } else {
                _cdrAlign(_buf, _cdrBase, 4); _buf.getInt();
            }
            if ((_want & (1L << 6)) != 0) {
                _cdrAlign(_buf, _cdrBase, 4); _out.u32_val = _buf.getInt();
            } else {
                _cdrAlign(_buf, _cdrBase, 4); _buf.getInt();
            }
            if ((_want & (1L << 7)) != 0) {
                _cdrAlign(_buf, _cdrBase, _xcdrVersion == 1 ? 8 : 4); _out.s64_val = _buf.getLong();
            } else {
                _cdrAlign(_buf, _cdrBase, _xcdrVersion == 1 ? 8 : 4); _buf.getLong();
            }
            if ((_want & (1L << 8)) != 0) {
                _cdrAlign(_buf, _cdrBase, _xcdrVersion == 1 ? 8 : 4); _out.u64_val = _buf.getLong();
            } else {
                _cdrAlign(_buf, _cdrBase, _xcdrVersion == 1 ? 8 : 4); _buf.getLong();
            }
            if ((_want & (1L << 9)) != 0) {
                _cdrAlign(_buf, _cdrBase, 4); _out.f32_val = _buf.getFloat();
            } else {
                _cdrAlign(_buf, _cdrBase, 4); _buf.getInt();
            }
            if ((_want & (1L << 10)) != 0) {
                _cdrAlign(_buf, _cdrBase, _xcdrVersion == 1 ? 8 : 4); _out.f64_val = _buf.getDouble();
            } else {
                _cdrAlign(_buf, _cdrBase, _xcdrVersion == 1 ? 8 : 4); _buf.getLong();
            }
            if ((_want & (1L << 11)) != 0) {
                _out.str = _cdrReadString(_buf, _cdrBase);
            } else {
                _cdrReadString(_buf, _cdrBase);
            }
            if ((_want & (1L << 12)) != 0) {
                _out.bstr = _cdrReadString(_buf, _cdrBase);
            } else {
                _cdrReadString(_buf, _cdrBase);
            }
            if ((_want & (1L << 13)) != 0) {
                _cdrAlign(_buf, _cdrBase, 4); int _n__out_nums = _buf.getInt();
                _out.nums = new java.util.ArrayList<>(_n__out_nums);
                for (int _i__out_nums = 0; _i__out_nums < _n__out_nums; _i__out_nums++) {
                    _cdrAlign(_buf, _cdrBase, 4); _out.nums.add(_buf.getInt());
                }
            } else {
                { _cdrAlign(_buf, _cdrBase, 4); int _n = _buf.getInt();
                  for (int _i = 0; _i < _n; _i++) {
                    _cdrAlign(_buf, _cdrBase, 4); _buf.getInt();
                  }
                }
            }
            if ((_want & (1L << 14)) != 0) {
                for (int _d0 = 0; _d0 < 3; _d0++) {
                    _cdrAlign(_buf, _cdrBase, 4); _out.arr[_d0] = _buf.getInt();
                }
            } else {
                for (int _sk0 = 0; _sk0 < 3; _sk0++) {
                    _cdrAlign(_buf, _cdrBase, 4); _buf.getInt();
                }
            }
            if ((_want & (1L << 15)) != 0) {
                _cdrAlign(_buf, _cdrBase, 4); _out.clr = Color.valueOf(_buf.getInt());
            } else {
                _cdrAlign(_buf, _cdrBase, 4); _buf.getInt();
            }
            if ((_want & (1L << 16)) != 0) {
                _out.nested = Point.deserializeFrom(_buf, _cdrBase, _xcdrVersion);
            } else {
                Point.skip(_buf, _cdrBase, _xcdrVersion);
            }
            return _out;
        }
    } // Sample

    public static class Frame implements java.io.Serializable {
        private static final long serialVersionUID = 1L;
        private int seq_num;
        private String topic;

        public Frame() {
            this.seq_num = 0;
            this.topic = "";
        }

        public static Frame defaultValue() {
            return new Frame();
        }

        public Frame(int seq_num, String topic) {
            this.seq_num = seq_num;
            this.topic = topic;
        }

        public int get_seq_num() { return seq_num; }
        public void set_seq_num(int seq_num) { this.seq_num = seq_num; }

        public String get_topic() { return topic; }
        public void set_topic(String topic) { this.topic = topic; }

        public static final boolean HAS_KEY = false;

        public void serialize(java.nio.ByteBuffer _buf, int _cdrBase, int _xcdrVersion) {
            _buf.order(java.nio.ByteOrder.LITTLE_ENDIAN);
            int _dhPos = 0;
            if (_xcdrVersion == 2) { _cdrAlign(_buf, _cdrBase, 4); _dhPos = _buf.position(); _buf.putInt(0); }
            _cdrAlign(_buf, _cdrBase, 4); _buf.putInt(this.seq_num);
            _cdrWriteString(_buf, _cdrBase, this.topic);
            if (_xcdrVersion == 2) { _buf.putInt(_dhPos, _buf.position() - _dhPos - 4); }
        }

        public static Frame deserializeFrom(java.nio.ByteBuffer _buf, int _cdrBase, int _xcdrVersion) {
            _buf.order(java.nio.ByteOrder.LITTLE_ENDIAN);
            Frame _out = new Frame();
            if (_xcdrVersion == 2) { _cdrAlign(_buf, _cdrBase, 4); _buf.getInt(); } // skip DHEADER
            _cdrAlign(_buf, _cdrBase, 4); _out.seq_num = _buf.getInt();
            _out.topic = _cdrReadString(_buf, _cdrBase);
            return _out;
        }

        public static void skip(java.nio.ByteBuffer _buf, int _cdrBase, int _xcdrVersion) {
            _buf.order(java.nio.ByteOrder.LITTLE_ENDIAN);
            if (_xcdrVersion == 2) {
                _cdrAlign(_buf, _cdrBase, 4); int _end = _buf.position() + 4 + _buf.getInt();
                _buf.position(_end);
            } else {
                _cdrAlign(_buf, _cdrBase, 4); _buf.getInt();
                _cdrReadString(_buf, _cdrBase);
            }
        }
    } // Frame

    public static class Beacon implements java.io.Serializable {
        private static final long serialVersionUID = 1L;
        private int id;
        private String payload;

        public Beacon() {
            this.id = 0;
            this.payload = "";
        }

        public static Beacon defaultValue() {
            return new Beacon();
        }

        public Beacon(int id, String payload) {
            this.id = id;
            this.payload = payload;
        }

        public int get_id() { return id; }
        public void set_id(int id) { this.id = id; }

        public String get_payload() { return payload; }
        public void set_payload(String payload) { this.payload = payload; }

        public static final boolean HAS_KEY = true;

        public void serialize(java.nio.ByteBuffer _buf, int _cdrBase, int _xcdrVersion) {
            _buf.order(java.nio.ByteOrder.LITTLE_ENDIAN);
            int _dhPos = 0;
            if (_xcdrVersion == 2) { _cdrAlign(_buf, _cdrBase, 4); _dhPos = _buf.position(); _buf.putInt(0); }
            _cdrAlign(_buf, _cdrBase, 4); _buf.putInt(this.id);
            _cdrWriteString(_buf, _cdrBase, this.payload);
            if (_xcdrVersion == 2) { _buf.putInt(_dhPos, _buf.position() - _dhPos - 4); }
        }

        public static Beacon deserializeFrom(java.nio.ByteBuffer _buf, int _cdrBase, int _xcdrVersion) {
            _buf.order(java.nio.ByteOrder.LITTLE_ENDIAN);
            Beacon _out = new Beacon();
            if (_xcdrVersion == 2) { _cdrAlign(_buf, _cdrBase, 4); _buf.getInt(); } // skip DHEADER
            _cdrAlign(_buf, _cdrBase, 4); _out.id = _buf.getInt();
            _out.payload = _cdrReadString(_buf, _cdrBase);
            return _out;
        }

        public static void skip(java.nio.ByteBuffer _buf, int _cdrBase, int _xcdrVersion) {
            _buf.order(java.nio.ByteOrder.LITTLE_ENDIAN);
            if (_xcdrVersion == 2) {
                _cdrAlign(_buf, _cdrBase, 4); int _end = _buf.position() + 4 + _buf.getInt();
                _buf.position(_end);
            } else {
                _cdrAlign(_buf, _cdrBase, 4); _buf.getInt();
                _cdrReadString(_buf, _cdrBase);
            }
        }

        protected void serializeKeyFields(java.nio.ByteBuffer _buf, int _cdrBase, int _xcdrVersion) {
            _cdrAlign(_buf, _cdrBase, 4); _buf.putInt(this.id);
        }

        public void serializeKey(java.nio.ByteBuffer _buf, int _cdrBase, int _xcdrVersion) {
            _buf.order(java.nio.ByteOrder.LITTLE_ENDIAN);
            int _dhPos = 0;
            if (_xcdrVersion == 2) { _cdrAlign(_buf, _cdrBase, 4); _dhPos = _buf.position(); _buf.putInt(0); }
            serializeKeyFields(_buf, _cdrBase, _xcdrVersion);
            if (_xcdrVersion == 2) { _buf.putInt(_dhPos, _buf.position() - _dhPos - 4); }
        }

        public static Beacon deserializeKey(java.nio.ByteBuffer _buf, int _cdrBase, int _xcdrVersion) {
            _buf.order(java.nio.ByteOrder.LITTLE_ENDIAN);
            Beacon _out = new Beacon();
            deserializeKeyInto(_out, _buf, _cdrBase, _xcdrVersion);
            return _out;
        }

        protected static void deserializeKeyInto(Beacon _out, java.nio.ByteBuffer _buf, int _cdrBase, int _xcdrVersion) {
            int _keyEnd = 0;
            if (_xcdrVersion == 2) { _cdrAlign(_buf, _cdrBase, 4); _keyEnd = _buf.position() + 4 + _buf.getInt(); }
            if (_xcdrVersion != 2) {
            }
            _cdrAlign(_buf, _cdrBase, 4); _out.id = _buf.getInt();
            if (_xcdrVersion == 2) { _buf.position(_keyEnd); }
        }

        public byte[] computeKeyHash() {
            int _cap = 256;
            while (true) {
                java.nio.ByteBuffer _buf = java.nio.ByteBuffer.allocate(_cap).order(java.nio.ByteOrder.BIG_ENDIAN);
                try {
                    serializeKeyFields(_buf, 0, 1);
                    return _cdrComputeKeyHash(_buf);
                } catch (java.nio.BufferOverflowException _e) {
                    _cap *= 2;
                }
            }
        }

        public static byte[] computeKeyHashFromCdr(byte[] _payload) {
            java.nio.ByteBuffer _buf = java.nio.ByteBuffer.wrap(_payload).order(java.nio.ByteOrder.LITTLE_ENDIAN);
            int _xcdrVersion = _cdrDetectXcdr(_payload);
            _buf.position(4);
            Beacon _obj = deserializeFrom(_buf, 4, _xcdrVersion);
            return _obj.computeKeyHash();
        }

        public static Object getFieldFromCdr(byte[] _payload, String _field) {
            java.nio.ByteBuffer _buf = java.nio.ByteBuffer.wrap(_payload).order(java.nio.ByteOrder.LITTLE_ENDIAN);
            int _xcdrVersion = _cdrDetectXcdr(_payload);
            _buf.position(4);
            int _fi = fieldIndex(_field);
            Beacon _obj = deserializeSelected(_buf, 4, _xcdrVersion, _fi < 0 ? 0L : (1L << _fi));
            switch (_field) {
                case "id": return (long) _obj.id;
                case "payload": return _obj.payload;
                default: return null;
            }
        }

        public static final long KEY_FIELD_MASK = (1L << 0);
        public static int fieldIndex(String _name) {
            switch (_name) {
                case "id": return 0;
                case "payload": return 1;
                default: return -1;
            }
        }

        public static Beacon deserializeSelected(java.nio.ByteBuffer _buf, int _cdrBase, int _xcdrVersion, long _want) {
            _buf.order(java.nio.ByteOrder.LITTLE_ENDIAN);
            Beacon _out = new Beacon();
            if (_xcdrVersion == 2) { _cdrAlign(_buf, _cdrBase, 4); _buf.getInt(); } // skip DHEADER
            if ((_want & (1L << 0)) != 0) {
                _cdrAlign(_buf, _cdrBase, 4); _out.id = _buf.getInt();
            } else {
                _cdrAlign(_buf, _cdrBase, 4); _buf.getInt();
            }
            if ((_want & (1L << 1)) != 0) {
                _out.payload = _cdrReadString(_buf, _cdrBase);
            } else {
                _cdrReadString(_buf, _cdrBase);
            }
            return _out;
        }
    } // Beacon

    public interface Greeter {
        String greet(String name);
        void reset();
        int get_count();
    } // interface Greeter

    public interface AdvancedGreeter extends Greeter {
        void greetAdvanced(String name);
    } // interface AdvancedGreeter

}
