/* Generated by zidl from types.idl — DO NOT EDIT */

#ifndef TYPES_H
#define TYPES_H

#include <stdint.h>
#include <stdbool.h>
#include "zidl_cdr.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    Color_RED = 0,
    Color_GREEN = 1,
    Color_BLUE = 2
} Color;

typedef struct { void *ptr; const void *vtable; } Greeter;
typedef struct { void *ptr; const void *vtable; } AdvancedGreeter;

#ifndef INT32_T_SEQ_DEFINED
#define INT32_T_SEQ_DEFINED
typedef struct {
    uint32_t _maximum;
    uint32_t _length;
    int32_t *_buffer;
    bool _release;
} int32_t_seq;
#endif

typedef struct Point_s {
    int32_t x;
    int32_t y;
} Point;

#define Point_has_key 0
int Point_serialize(ZidlCdrWriter *_w, const Point *_v);
int Point_deserialize(ZidlCdrReader *_r, Point *_v);
int Point_skip(ZidlCdrReader *_r);

/* Initialize uninitialized storage using IDL defaults and zero values. */
void Point_default(Point *_v);

typedef struct Sample_s {
    uint32_t id;
    bool b;
    uint8_t u8_val;
    int16_t s16_val;
    uint16_t u16_val;
    int32_t s32_val;
    uint32_t u32_val;
    int64_t s64_val;
    uint64_t u64_val;
    float f32_val;
    double f64_val;
    char *str;
    char bstr[33];
    int32_t_seq nums;
    int32_t arr[3];
    Color clr;
    Point nested;
} Sample;

#define Sample_has_key 1
int Sample_serialize(ZidlCdrWriter *_w, const Sample *_v);
int Sample_deserialize(ZidlCdrReader *_r, Sample *_v);
int Sample_skip(ZidlCdrReader *_r);
int Sample_serialize_key(ZidlCdrWriter *_w, const Sample *_v);
int Sample_deserialize_key(ZidlCdrReader *_r, Sample *_v);
int Sample_compute_key_hash(const Sample *_v, uint8_t _hash[16]);
int Sample_compute_key_hash_from_cdr(const uint8_t *_payload, size_t _len, uint8_t _hash[16]);

/* Initialize uninitialized storage using IDL defaults and zero values. Not a reset operation: release any owned fields before reinitializing an existing object. */
void Sample_default(Sample *_v);

void Sample_free(Sample *v);

typedef struct Frame_s {
    uint32_t seq_num;
    char *topic;
} Frame;

#define Frame_has_key 0
int Frame_serialize(ZidlCdrWriter *_w, const Frame *_v);
int Frame_deserialize(ZidlCdrReader *_r, Frame *_v);
int Frame_skip(ZidlCdrReader *_r);

/* Initialize uninitialized storage using IDL defaults and zero values. Not a reset operation: release any owned fields before reinitializing an existing object. */
void Frame_default(Frame *_v);

typedef struct Beacon_s {
    uint32_t id;
    char *payload;
} Beacon;

#define Beacon_has_key 1
int Beacon_serialize(ZidlCdrWriter *_w, const Beacon *_v);
int Beacon_deserialize(ZidlCdrReader *_r, Beacon *_v);
int Beacon_skip(ZidlCdrReader *_r);
int Beacon_serialize_key(ZidlCdrWriter *_w, const Beacon *_v);
int Beacon_deserialize_key(ZidlCdrReader *_r, Beacon *_v);
int Beacon_compute_key_hash(const Beacon *_v, uint8_t _hash[16]);
int Beacon_compute_key_hash_from_cdr(const uint8_t *_payload, size_t _len, uint8_t _hash[16]);

/* Initialize uninitialized storage using IDL defaults and zero values. Not a reset operation: release any owned fields before reinitializing an existing object. */
void Beacon_default(Beacon *_v);

/* IDL interface: Greeter */
char *Greeter_greet(Greeter self, const char *name);
void Greeter_reset(Greeter self);
int32_t Greeter_get_count(Greeter self);

/* IDL interface: AdvancedGreeter */
char *AdvancedGreeter_greet(AdvancedGreeter self, const char *name);
void AdvancedGreeter_reset(AdvancedGreeter self);
void AdvancedGreeter_greetAdvanced(AdvancedGreeter self, const char *name);
int32_t AdvancedGreeter_get_count(AdvancedGreeter self);
/* Cast helpers are emitted for direct inheritance edges; compose helpers for transitive casts. */
/* Upcast AdvancedGreeter to Greeter. */
Greeter AdvancedGreeter_as_Greeter(AdvancedGreeter child);
/* Downcast Greeter to AdvancedGreeter; returns a null handle when the base object is not an instance of AdvancedGreeter. */
AdvancedGreeter Greeter_as_AdvancedGreeter(Greeter base);


#ifdef __cplusplus
}
#endif
#endif /* TYPES_H */
