// Synthetic condition hierarchy: exercise the same shared-box inheritance and
// raw-loan parameter adaptation as DDS without depending on a middleware.
module DDS {
    typedef sequence<octet> OctetSeq;
    typedef sequence<OctetSeq> OctetSeqSeq;
    struct SampleInfo { boolean valid_data; };
    typedef sequence<SampleInfo> SampleInfoSeq;
    @shared_c_abi_box interface Condition {};
    @shared_c_abi_box interface GuardCondition : Condition {};
    @shared_c_abi_box interface StatusCondition : Condition {};
    @shared_c_abi_box interface ReadCondition : Condition {};
    @shared_c_abi_box interface QueryCondition : ReadCondition {};
    interface DataReader {
        DataReader get_reader();
        Condition get_condition();
        ReadCondition get_readcondition();
        QueryCondition get_querycondition();
        GuardCondition get_guardcondition();
        StatusCondition get_statuscondition();
        long take_raw(inout OctetSeqSeq cdr_payloads, inout OctetSeq key_hashes, inout SampleInfoSeq sample_infos, in long instance_handle, in ReadCondition a_condition, in unsigned long sample_states, in unsigned long view_states, in unsigned long instance_states, in long max_samples);
        long read_raw(inout OctetSeqSeq cdr_payloads, inout OctetSeq key_hashes, inout SampleInfoSeq sample_infos, in long instance_handle, in ReadCondition a_condition, in unsigned long sample_states, in unsigned long view_states, in unsigned long instance_states, in long max_samples);
        long take_next_instance_raw(inout OctetSeqSeq cdr_payloads, inout OctetSeq key_hashes, inout SampleInfoSeq sample_infos, in long previous_handle, in ReadCondition a_condition, in unsigned long sample_states, in unsigned long view_states, in unsigned long instance_states, in long max_samples);
        long read_next_instance_raw(inout OctetSeqSeq cdr_payloads, inout OctetSeq key_hashes, inout SampleInfoSeq sample_infos, in long previous_handle, in ReadCondition a_condition, in unsigned long sample_states, in unsigned long view_states, in unsigned long instance_states, in long max_samples);
    };
};
