// Generated by zidl from types.idl — DO NOT EDIT

import java.util.List;
import java.util.ArrayList;

public interface AdvancedGreeter extends Greeter {
    void greetAdvanced(String name);
} // interface AdvancedGreeter

