// Generated by zidl from types.idl — DO NOT EDIT

import java.util.List;
import java.util.ArrayList;
import static TypesCdrUtils.*;

public class Beacon implements java.io.Serializable {
    private static final long serialVersionUID = 1L;
    private int id;
    private String payload;

    public Beacon() {
        this.id = 0;
        this.payload = "";
    }

    public Beacon(int id, String payload) {
        this.id = id;
        this.payload = payload;
    }

    public int get_id() { return id; }
    public void set_id(int id) { this.id = id; }

    public String get_payload() { return payload; }
    public void set_payload(String payload) { this.payload = payload; }

    public static final boolean HAS_KEY = true;

    public void serialize(java.nio.ByteBuffer _buf, int _cdrBase) {
        _buf.order(java.nio.ByteOrder.LITTLE_ENDIAN);
        _cdrAlign(_buf, _cdrBase, 4);
        int _dhPos = _buf.position(); _buf.putInt(0);
        _cdrAlign(_buf, _cdrBase, 4); _buf.putInt(this.id);
        _cdrWriteString(_buf, _cdrBase, this.payload);
        _buf.putInt(_dhPos, _buf.position() - _dhPos - 4);
    }

    public static Beacon deserializeFrom(java.nio.ByteBuffer _buf, int _cdrBase) {
        _buf.order(java.nio.ByteOrder.LITTLE_ENDIAN);
        Beacon _out = new Beacon();
        _cdrAlign(_buf, _cdrBase, 4); _buf.getInt(); // skip DHEADER
        _cdrAlign(_buf, _cdrBase, 4); _out.id = _buf.getInt();
        _out.payload = _cdrReadString(_buf, _cdrBase);
        return _out;
    }

    public static void skip(java.nio.ByteBuffer _buf, int _cdrBase) {
        _buf.order(java.nio.ByteOrder.LITTLE_ENDIAN);
        _cdrAlign(_buf, _cdrBase, 4); int _end = _buf.position() + 4 + _buf.getInt();
        _buf.position(_end);
    }

    protected void serializeKeyFields(java.nio.ByteBuffer _buf, int _cdrBase) {
        _cdrAlign(_buf, _cdrBase, 4); _buf.putInt(this.id);
    }

    public void serializeKey(java.nio.ByteBuffer _buf, int _cdrBase) {
        _buf.order(java.nio.ByteOrder.LITTLE_ENDIAN);
        _cdrAlign(_buf, _cdrBase, 4); int _dhPos = _buf.position(); _buf.putInt(0);
        serializeKeyFields(_buf, _cdrBase);
        _buf.putInt(_dhPos, _buf.position() - _dhPos - 4);
    }

    public static Beacon deserializeKey(java.nio.ByteBuffer _buf, int _cdrBase) {
        _buf.order(java.nio.ByteOrder.LITTLE_ENDIAN);
        Beacon _out = new Beacon();
        deserializeKeyInto(_out, _buf, _cdrBase);
        return _out;
    }

    protected static void deserializeKeyInto(Beacon _out, java.nio.ByteBuffer _buf, int _cdrBase) {
        _cdrAlign(_buf, _cdrBase, 4); int _keyEnd = _buf.position() + 4 + _buf.getInt();
        _cdrAlign(_buf, _cdrBase, 4); _out.id = _buf.getInt();
        _buf.position(_keyEnd);
    }

    public byte[] computeKeyHash() {
        int _cap = 256;
        while (true) {
            java.nio.ByteBuffer _buf = java.nio.ByteBuffer.allocate(_cap).order(java.nio.ByteOrder.BIG_ENDIAN);
            try {
                serializeKeyFields(_buf, 0);
                return _cdrComputeKeyHash(_buf);
            } catch (java.nio.BufferOverflowException _e) {
                _cap *= 2;
            }
        }
    }
} // Beacon

