// Generated by zidl from types.idl — DO NOT EDIT

#ifndef ADVANCEDGREETER_HPP
#define ADVANCEDGREETER_HPP

#include <cstdint>
#include <string>
#include <vector>
#include <array>
#include <stdexcept>
#include "Greeter.hpp"

class AdvancedGreeter : public ::Greeter {
public:
    virtual ~AdvancedGreeter() = default;
    virtual void greetAdvanced(std::string name) = 0;
}; // class AdvancedGreeter

#endif // ADVANCEDGREETER_HPP
