// Generated by zidl from types.idl — DO NOT EDIT

#ifndef BEACON_HPP
#define BEACON_HPP

#include <cstdint>
#include <string>
#include <vector>
#include <array>
#include <stdexcept>
#include "zidl_cdr.h"

struct Beacon {
    uint32_t id{};
    std::string payload{};
}; // struct Beacon

#define Beacon_has_key 1
int Beacon_serialize(ZidlCdrWriter *_w, const ::Beacon *_v);
int Beacon_deserialize(ZidlCdrReader *_r, ::Beacon *_v);
int Beacon_skip(ZidlCdrReader *_r);
int Beacon_serialize_key(ZidlCdrWriter *_w, const ::Beacon *_v);
int Beacon_deserialize_key(ZidlCdrReader *_r, ::Beacon *_v);
int Beacon_compute_key_hash(const ::Beacon *_v, uint8_t _hash[16]);

#endif // BEACON_HPP
