// Generated by zidl from types.idl — DO NOT EDIT

#include "types.hpp"

// ── interface Greeter ──

extern "C" {
char * zidl_Greeter_greet(void *ptr, char * name);
void zidl_Greeter_reset(void *ptr);
int32_t zidl_Greeter_get_count(void *ptr);
void zidl_Greeter_deinit(void *ptr);
}

class GreeterImpl : public ::Greeter {
public:
    explicit GreeterImpl(void *ptr) : ptr_(ptr) {}
    ~GreeterImpl() override { zidl_Greeter_deinit(ptr_); }

    std::string greet(std::string name) override {
        return std::string(zidl_Greeter_greet(ptr_, name.c_str()));
    }
    void reset() override {
        zidl_Greeter_reset(ptr_);
    }
    int32_t count() const override {
        return zidl_Greeter_get_count(ptr_);
    }
private:
    void *ptr_;
};

// ── interface AdvancedGreeter ──

extern "C" {
char * zidl_AdvancedGreeter_greet(void *ptr, char * name);
void zidl_AdvancedGreeter_reset(void *ptr);
void zidl_AdvancedGreeter_greetAdvanced(void *ptr, char * name);
int32_t zidl_AdvancedGreeter_get_count(void *ptr);
void zidl_AdvancedGreeter_deinit(void *ptr);
}

class AdvancedGreeterImpl : public ::AdvancedGreeter {
public:
    explicit AdvancedGreeterImpl(void *ptr) : ptr_(ptr) {}
    ~AdvancedGreeterImpl() override { zidl_AdvancedGreeter_deinit(ptr_); }

    std::string greet(std::string name) override {
        return std::string(zidl_AdvancedGreeter_greet(ptr_, name.c_str()));
    }
    void reset() override {
        zidl_AdvancedGreeter_reset(ptr_);
    }
    void greetAdvanced(std::string name) override {
        zidl_AdvancedGreeter_greetAdvanced(ptr_, name.c_str());
    }
    int32_t count() const override {
        return zidl_AdvancedGreeter_get_count(ptr_);
    }
private:
    void *ptr_;
};

