/* Generated by zidl from types.idl — DO NOT EDIT */

#ifndef ADVANCEDGREETER_H
#define ADVANCEDGREETER_H

#include <stdint.h>
#include <stdbool.h>
#include "Greeter.h"

typedef struct { void *ptr; const void *vtable; } AdvancedGreeter;

/* IDL interface: AdvancedGreeter */
char *AdvancedGreeter_greet(AdvancedGreeter self, const char *name);
void AdvancedGreeter_reset(AdvancedGreeter self);
void AdvancedGreeter_greetAdvanced(AdvancedGreeter self, const char *name);
int32_t AdvancedGreeter_get_count(AdvancedGreeter self);

#endif /* ADVANCEDGREETER_H */
