/* Generated by zidl from types.idl — DO NOT EDIT */

#include "Beacon.h"
#include "zidl_cdr.h"
#include <string.h>

int Beacon_serialize(ZidlCdrWriter *_w, const Beacon *_v) {
    int _rc;
    size_t _dh;
    _rc = zidl_cdr_reserve_dheader_maybe(_w, &_dh);
    if (_rc) return _rc;
    _rc = zidl_cdr_write_u32(_w, _v->id);
    if (_rc) return _rc;
    _rc = zidl_cdr_write_string(_w, _v->payload ? _v->payload : "", _v->payload ? (uint32_t)strlen(_v->payload) : 0u);
    if (_rc) return _rc;
    zidl_cdr_patch_dheader_maybe(_w, _dh);
    return ZIDL_CDR_OK;
}

int Beacon_deserialize(ZidlCdrReader *_r, Beacon *_v) {
    int _rc;
    _rc = zidl_cdr_skip_dheader_if_xcdr2(_r);
    if (_rc) return _rc;
    _rc = zidl_cdr_read_u32(_r, &_v->id);
    if (_rc) return _rc;
    _rc = zidl_cdr_read_string(_r, &_v->payload);
    if (_rc) return _rc;
    return ZIDL_CDR_OK;
}

int Beacon_skip(ZidlCdrReader *_r) {
    int _rc;
    if (_r->xcdr_version == ZIDL_XCDR2) {
        uint32_t _size;
        _rc = zidl_cdr_read_dheader(_r, &_size);
        if (_rc) return _rc;
        return zidl_cdr_skip(_r, _size);
    }
    { uint32_t _tmp; _rc = zidl_cdr_read_u32(_r, &_tmp); if (_rc) return _rc; }
    { const char *_sp; uint32_t _sl; _rc = zidl_cdr_read_string_zerocopy(_r, &_sp, &_sl); if (_rc) return _rc; }
    return ZIDL_CDR_OK;
}

int Beacon_serialize_key(ZidlCdrWriter *_w, const Beacon *_v) {
    int _rc;
    size_t _dh;
    _rc = zidl_cdr_reserve_dheader_maybe(_w, &_dh);
    if (_rc) return _rc;
    _rc = zidl_cdr_write_u32(_w, _v->id);
    if (_rc) return _rc;
    zidl_cdr_patch_dheader_maybe(_w, _dh);
    return ZIDL_CDR_OK;
}

int Beacon_deserialize_key(ZidlCdrReader *_r, Beacon *_v) {
    int _rc;
    size_t _key_end = (size_t)-1;
    if (_r->xcdr_version == ZIDL_XCDR2) {
        uint32_t _size;
        _rc = zidl_cdr_read_dheader(_r, &_size);
        if (_rc) return _rc;
        _key_end = _r->pos + (size_t)_size;
    }
    _rc = zidl_cdr_read_u32(_r, &_v->id);
    if (_rc) return _rc;
    if (_key_end != (size_t)-1) { _rc = zidl_cdr_seek_to(_r, _key_end); if (_rc) return _rc; }
    return ZIDL_CDR_OK;
}

int Beacon_compute_key_hash(const Beacon *_v, uint8_t _hash[16]) {
    ZidlCdrWriter _w;
    int _rc = zidl_cdr_writer_init(&_w, ZIDL_XCDR1);
    if (_rc) return _rc;
    zidl_cdr_writer_set_byte_order(&_w, ZIDL_CDR_BE);
    _rc = Beacon_serialize_key(&_w, _v);
    if (!_rc) zidl_cdr_compute_key_hash(_w.buf, _w.len, _hash);
    zidl_cdr_writer_deinit(&_w);
    return _rc;
}

int Beacon_compute_key_hash_from_cdr(const uint8_t *_payload, size_t _len, uint8_t _hash[16]) {
    ZidlCdrReader _r_data;
    int _rc = zidl_cdr_reader_init(&_r_data, _payload, _len);
    if (_rc) return _rc;
    ZidlCdrReader *_r = &_r_data;
    Beacon _v_data;
    memset(&_v_data, 0, sizeof(Beacon));
    Beacon *_v = &_v_data;
    size_t _key_end = (size_t)-1;
    if (_r->xcdr_version == ZIDL_XCDR2) {
        uint32_t _dh_size;
        _rc = zidl_cdr_read_dheader(_r, &_dh_size);
        if (_rc) return _rc;
        _key_end = _r->pos + (size_t)_dh_size;
    }
    _rc = zidl_cdr_read_u32(_r, &_v->id);
    if (_rc) return _rc;
    if (_key_end != (size_t)-1) { _rc = zidl_cdr_seek_to(_r, _key_end); if (_rc) return _rc; }
    return Beacon_compute_key_hash(_v, _hash);
}

void Beacon_default(Beacon *_v) {
    memset(_v, 0, sizeof(*_v));
}

