/* Generated by zidl from types.idl — DO NOT EDIT */

#ifndef BEACON_H
#define BEACON_H

#include <stdint.h>
#include <stdbool.h>
#include "zidl_cdr.h"

typedef struct Beacon_s {
    uint32_t id;
    char *payload;
} Beacon;

#define Beacon_has_key 1
int Beacon_serialize(ZidlCdrWriter *_w, const Beacon *_v);
int Beacon_deserialize(ZidlCdrReader *_r, Beacon *_v);
int Beacon_skip(ZidlCdrReader *_r);
int Beacon_serialize_key(ZidlCdrWriter *_w, const Beacon *_v);
int Beacon_deserialize_key(ZidlCdrReader *_r, Beacon *_v);
int Beacon_compute_key_hash(const Beacon *_v, uint8_t _hash[16]);
int Beacon_compute_key_hash_from_cdr(const uint8_t *_payload, size_t _len, uint8_t _hash[16]);

/* Initialize uninitialized storage using IDL defaults and zero values. Not a reset operation: release any owned fields before reinitializing an existing object. */
void Beacon_default(Beacon *_v);

void Beacon_free(Beacon *v);

#endif /* BEACON_H */
