/* Generated by zidl from types.idl — DO NOT EDIT */

#ifndef GREETER_H
#define GREETER_H

#include <stdint.h>
#include <stdbool.h>

/* IDL interface: Greeter */
char *Greeter_greet(Greeter self, char *name);
void Greeter_reset(Greeter self);
int32_t Greeter_get_count(Greeter self);

#endif /* GREETER_H */
